CREATE TABLE IF NOT EXISTS MPA_RATINGS (
    mpa_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS GENRES (
    genre_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS FILMS (
    film_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    mpa_id INT REFERENCES MPA_RATINGS(mpa_id)
    );

CREATE TABLE IF NOT EXISTS USERS (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL,
    birthday DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS LIKES (
    film_id INT NOT NULL REFERENCES FILMS(film_id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES USERS(user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

CREATE TABLE IF NOT EXISTS FILM_GENRES (
    film_id INT NOT NULL REFERENCES FILMS(film_id) ON DELETE CASCADE,
    genre_id INT NOT NULL REFERENCES GENRES(genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS FRIENDS (
    user_id INT NOT NULL REFERENCES USERS(user_id) ON DELETE CASCADE,
    friend_id INT NOT NULL REFERENCES USERS(user_id) ON DELETE CASCADE,
    status BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id)
    );
